### ISSUE TITLE
QVD-DB prerequisite DBD::Pg fails to install

### ISSUE THREAD

**Issue by HenrikBach1** [theqvd/git-qvd#3]
Hi,

When compiling code for QVD-DB it needs the prerequisite DBD::Pg. However, it fails when installing:

cpanm DBD::Pg
--> Working on DBD::Pg
Fetching http://www.cpan.org/authors/id/T/TU/TURNSTEP/DBD-Pg-3.5.3.tar.gz ... OK
Configuring DBD-Pg-3.5.3 ... N/A
! Configure failed for DBD-Pg-3.5.3. See /root/.cpanm/work/1482261787.8572/[build.log.txt](https://github.com/theqvd/git-qvd/files/664570/build.log.txt) for details.

What can/should I do?

/Henrik

**Comment by salva** [comment]
You need to install the PostgreSQL client library `libpq` development package. Something like `libpq-dev`.
